Repository card-monkey/card-monkey-BE, pull requests merged in 2023-02, with the labels that each got.

#3 feat: Create Entity
  src/main/java/com/example/cardmonkey/entity/Benefit.java
  src/main/java/com/example/cardmonkey/entity/Card.java
  src/main/java/com/example/cardmonkey/entity/CardType.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/FavorCard.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/entity/PaidCard.java
  src/main/java/com/example/cardmonkey/entity/Review.java
Labels: Status: In Progress, For: Backend, Priority: High, Type: Feature

#4 엔티티 연관관계 설정
  src/main/java/com/example/cardmonkey/entity/Benefit.java
  src/main/java/com/example/cardmonkey/entity/Card.java
  src/main/java/com/example/cardmonkey/entity/CardType.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/FavorCard.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/entity/PaidCard.java
  src/main/java/com/example/cardmonkey/entity/Review.java
Labels: Status: In Progress, For: Backend, Priority: High, Type: Feature

#10 카드 엔티티 수정
  src/main/java/com/example/cardmonkey/entity/Card.java
Labels: Status: Completed, For: Backend, Priority: High, Type: Feature

#11 엔티티 생성 관련 작업 반영
  src/main/java/com/example/cardmonkey/entity/Benefit.java
  src/main/java/com/example/cardmonkey/entity/Card.java
  src/main/java/com/example/cardmonkey/entity/CardType.java
  src/main/java/com/example/cardmonkey/entity/Comment.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/FavorCard.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/entity/PaidCard.java
  src/main/java/com/example/cardmonkey/entity/Review.java
  src/main/java/com/example/cardmonkey/entity/ReviewComment.java
Labels: Status: Completed, For: Backend, Priority: High, Type: Feature

#19 feat: Update Entity
  src/main/java/com/example/cardmonkey/entity/Benefit.java
  src/main/java/com/example/cardmonkey/entity/Card.java
  src/main/java/com/example/cardmonkey/entity/Member.java
Labels: Priority: Medium, Status: In Progress, For: Backend, Type: Feature

#20 인증관련기능
  src/main/java/com/example/cardmonkey/config/SwaggerConfig.java
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/dto/PasswordDTO.java
  src/main/java/com/example/cardmonkey/dto/SignupRequest.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Status: Completed, Type: Documentation, For: Backend, Priority: High, Type: Feature

#21 회원가입오류수정
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Status: Completed, For: Backend, Priority: High, Type: Feature

#22 로그아웃
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/dto/LoginRequest.java
  src/main/java/com/example/cardmonkey/dto/LoginResponse.java
  src/main/java/com/example/cardmonkey/dto/MemberDTO.java
  src/main/java/com/example/cardmonkey/dto/SignupRequest.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProperties.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Priority: Critical, Status: Completed, For: Backend, Type: Feature

#37 엔티티 수정 작업 및 .gitkeep 파일 삭제
  src/main/java/com/example/cardmonkey/config/.gitkeep
  src/main/java/com/example/cardmonkey/controller/.gitkeep
  src/main/java/com/example/cardmonkey/dto/.gitkeep
  src/main/java/com/example/cardmonkey/entity/.gitkeep
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/FavorCard.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/entity/PaidCard.java
  src/main/java/com/example/cardmonkey/entity/Token.java
  src/main/java/com/example/cardmonkey/jwt/.gitkeep
  src/main/java/com/example/cardmonkey/repository/.gitkeep
  src/main/java/com/example/cardmonkey/security/.gitkeep
  src/main/java/com/example/cardmonkey/service/.gitkeep
Labels: Status: Completed, For: Backend, Priority: High, Type: Feature

#38 CardServiceAndRepository
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/CardService.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Priority: Critical, Status: In Progress, For: Backend, Type: Maintenance, Type: Feature

#39 인증 기능 수정
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
Labels: For: API, Status: In Progress, For: Backend, Priority: High, Type: Bug

#40 찜 기능 완료
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/dto/FavorResponseDTO.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/repository/FavorRepository.java
  src/main/java/com/example/cardmonkey/service/CardService.java
Labels: For: API, Status: Completed, Priority: Medium, For: Backend, Type: Feature

#41 회원가입 기능 변경 및 혜택 변경, 관심 혜택 기반 카드 추천 기능 구현
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/controller/MemberController.java
  src/main/java/com/example/cardmonkey/dto/CardByBenefitResDTO.java
  src/main/java/com/example/cardmonkey/dto/ChangeBenefitReqDTO.java
  src/main/java/com/example/cardmonkey/dto/SignupReqDTO.java
  src/main/java/com/example/cardmonkey/entity/Benefit.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustom.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustomImpl.java
  src/main/java/com/example/cardmonkey/service/CardService.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Status: Completed, Priority: Medium, For: Backend, Type: Feature

#44 Develop : 검색 기능 구현 완료
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/dto/CardDTO.java
  src/main/java/com/example/cardmonkey/dto/CardDetailDTO.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/service/CardService.java
Labels: For: API, Status: Completed, Priority: Medium, For: Backend, Type: Feature

#45 feat: refactoring feature(search card detail)
  src/main/java/com/example/cardmonkey/controller/CardController.java
Labels: Priority: Medium, For: Backend, Type: Feature

#46 CORS
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/dto/MemberDTO.java
  src/main/java/com/example/cardmonkey/entity/Token.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
Labels: Priority: Medium, For: CI/CD, Status: In Progress, For: Backend, Type: Maintenance

#47 fix: Update Cors issue
  src/main/java/com/example/cardmonkey/config/WebConfig.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
Labels: Status: Completed, For: Backend, Priority: High, Type: Feature

#48 Logout
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/repository/TokenRepository.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/TokenService.java
Labels: For: API, Priority: Critical, Status: Completed, For: Backend, Type: Bug

#50 리팩토링 작업 일부 반영
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/controller/MemberController.java
  src/main/java/com/example/cardmonkey/dto/CardByBenefitResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardByFavorResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardDetailDTO.java
  src/main/java/com/example/cardmonkey/dto/CardDetailResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardResponseDTO.java
  src/main/java/com/example/cardmonkey/dto/FavorResDTO.java
  src/main/java/com/example/cardmonkey/dto/FavorResponseDTO.java
  src/main/java/com/example/cardmonkey/dto/LoginReqDTO.java
  src/main/java/com/example/cardmonkey/dto/LoginResDTO.java
  src/main/java/com/example/cardmonkey/dto/LoginResponse.java
  src/main/java/com/example/cardmonkey/dto/MemberDTO.java
  src/main/java/com/example/cardmonkey/dto/PaidReqDTO.java
  src/main/java/com/example/cardmonkey/dto/PaidResDTO.java
  src/main/java/com/example/cardmonkey/dto/PasswordReqDTO.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustom.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustomImpl.java
  src/main/java/com/example/cardmonkey/repository/FavorRepository.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/repository/PaidRepository.java
  src/main/java/com/example/cardmonkey/service/CardService.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Priority: Medium, Status: In Progress, For: Backend, Type: Feature

#51 리팩토링 작업 일부 반영
  src/main/java/com/example/cardmonkey/dto/CardByFavorResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardQueryDTO.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/FavorRepository.java
  src/main/java/com/example/cardmonkey/service/CardService.java
Labels: For: API, Priority: Medium, Status: In Progress, For: Backend, Type: Feature

#55 아이디 중복 체크
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/dto/ValidationDTO.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Status: Completed, For: Backend, Type: Feature, Priority: Low

#56 리팩토링 작업 일부 반영
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/controller/MemberController.java
  src/main/java/com/example/cardmonkey/dto/CardCountResDTO.java
  src/main/java/com/example/cardmonkey/dto/PasswordReqDTO.java
  src/main/java/com/example/cardmonkey/dto/ValidationDTO.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/entity/Token.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustom.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustomImpl.java
  src/main/java/com/example/cardmonkey/repository/FavorRepository.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/security/SecurityConfig.java
  src/main/java/com/example/cardmonkey/service/CardService.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
  src/main/java/com/example/cardmonkey/service/TokenService.java
Labels: For: API, Priority: Medium, Status: In Progress, For: Backend, Type: Feature

#58 리팩토링 작업 일부 반영
  src/main/java/com/example/cardmonkey/config/SecurityConfig.java
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/controller/MemberController.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#60 CardDetailResDTO 응답값 추가 및 기능 삭제
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/dto/CardDetailResDTO.java
  src/main/java/com/example/cardmonkey/dto/ReviewReqDTO.java
  src/main/java/com/example/cardmonkey/dto/ReviewResDTO.java
  src/main/java/com/example/cardmonkey/repository/CommentRepository.java
  src/main/java/com/example/cardmonkey/repository/ReviewRepository.java
  src/main/java/com/example/cardmonkey/service/CardService.java
Labels: For: API, Status: Completed, Priority: Medium, For: Backend, Type: Feature

#61 리팩토링 작업 일부 반영
  .gitignore
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/controller/MemberController.java
  src/main/java/com/example/cardmonkey/dto/AuthDTO.java
  src/main/java/com/example/cardmonkey/dto/CardQueryDTO.java
  src/main/java/com/example/cardmonkey/dto/FavorResDTO.java
  src/main/java/com/example/cardmonkey/dto/LoginReqDTO.java
  src/main/java/com/example/cardmonkey/dto/MemberDTO.java
  src/main/java/com/example/cardmonkey/dto/PaidReqDTO.java
  src/main/java/com/example/cardmonkey/dto/PaidResDTO.java
  src/main/java/com/example/cardmonkey/entity/Card.java
  src/main/java/com/example/cardmonkey/entity/Comment.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/entity/Review.java
  src/main/java/com/example/cardmonkey/entity/ReviewComment.java
  src/main/java/com/example/cardmonkey/exception/NoSuchCardException.java
  src/main/java/com/example/cardmonkey/exception/NoSuchMemberException.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProperties.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustom.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustomImpl.java
  src/main/java/com/example/cardmonkey/repository/FavorRepository.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/repository/PaidRepository.java
  src/main/java/com/example/cardmonkey/repository/TokenRepository.java
  src/main/java/com/example/cardmonkey/service/CardService.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
  src/main/java/com/example/cardmonkey/service/TokenService.java
Labels: For: API, Priority: Medium, Status: In Progress, For: Backend, Type: Feature

#64 카드 상세정보 오류 수정 및 최종 빌드를 위한 코드 정리 작업
  src/main/java/com/example/cardmonkey/config/SecurityConfig.java
  src/main/java/com/example/cardmonkey/dto/AuthDTO.java
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/service/CardService.java
Labels: Status: Completed, For: Backend, Type: Maintenance, Priority: High, Type: Feature

#65 프로젝트 작업 완료 메인 브랜치 반영
  .gitignore
  README.md
  src/main/java/com/example/cardmonkey/config/.gitkeep
  src/main/java/com/example/cardmonkey/config/SecurityConfig.java
  src/main/java/com/example/cardmonkey/config/SwaggerConfig.java
  src/main/java/com/example/cardmonkey/config/WebConfig.java
  src/main/java/com/example/cardmonkey/controller/.gitkeep
  src/main/java/com/example/cardmonkey/controller/AuthController.java
  src/main/java/com/example/cardmonkey/controller/CardController.java
  src/main/java/com/example/cardmonkey/controller/MemberController.java
  src/main/java/com/example/cardmonkey/dto/.gitkeep
  src/main/java/com/example/cardmonkey/dto/AuthDTO.java
  src/main/java/com/example/cardmonkey/dto/CardByBenefitResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardByFavorResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardCountResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardDetailResDTO.java
  src/main/java/com/example/cardmonkey/dto/CardResDTO.java
  src/main/java/com/example/cardmonkey/dto/ChangeBenefitReqDTO.java
  src/main/java/com/example/cardmonkey/dto/LoginReqDTO.java
  src/main/java/com/example/cardmonkey/dto/LoginResDTO.java
  src/main/java/com/example/cardmonkey/dto/PasswordReqDTO.java
  src/main/java/com/example/cardmonkey/dto/SignupReqDTO.java
  src/main/java/com/example/cardmonkey/dto/ValidationDTO.java
  src/main/java/com/example/cardmonkey/entity/.gitkeep
  src/main/java/com/example/cardmonkey/entity/Benefit.java
  src/main/java/com/example/cardmonkey/entity/Card.java
  src/main/java/com/example/cardmonkey/entity/Comment.java
  src/main/java/com/example/cardmonkey/entity/Favor.java
  src/main/java/com/example/cardmonkey/entity/FavorCard.java
  src/main/java/com/example/cardmonkey/entity/Member.java
  src/main/java/com/example/cardmonkey/entity/Paid.java
  src/main/java/com/example/cardmonkey/entity/PaidCard.java
  src/main/java/com/example/cardmonkey/entity/Review.java
  src/main/java/com/example/cardmonkey/entity/ReviewComment.java
  src/main/java/com/example/cardmonkey/entity/Token.java
  src/main/java/com/example/cardmonkey/exception/NoSuchCardException.java
  src/main/java/com/example/cardmonkey/exception/NoSuchMemberException.java
  src/main/java/com/example/cardmonkey/jwt/.gitkeep
  src/main/java/com/example/cardmonkey/jwt/JwtFilter.java
  src/main/java/com/example/cardmonkey/jwt/JwtProperties.java
  src/main/java/com/example/cardmonkey/jwt/JwtProvider.java
  src/main/java/com/example/cardmonkey/repository/.gitkeep
  src/main/java/com/example/cardmonkey/repository/CardRepository.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustom.java
  src/main/java/com/example/cardmonkey/repository/CardRepositoryCustomImpl.java
  src/main/java/com/example/cardmonkey/repository/FavorRepository.java
  src/main/java/com/example/cardmonkey/repository/MemberRepository.java
  src/main/java/com/example/cardmonkey/repository/PaidRepository.java
  src/main/java/com/example/cardmonkey/repository/TokenRepository.java
  src/main/java/com/example/cardmonkey/security/.gitkeep
  src/main/java/com/example/cardmonkey/service/.gitkeep
  src/main/java/com/example/cardmonkey/service/CardService.java
  src/main/java/com/example/cardmonkey/service/MemberService.java
  src/main/java/com/example/cardmonkey/service/TokenService.java
Labels: Status: Completed, Priority: Medium, For: Backend, Type: Maintenance
